# Generated by Django 3.0.5 on 2020-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('liguagem_atualmente', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'programador',
            },
        ),
    ]
