# Generated by Django 3.0.5 on 2020-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_programador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
